create or replace NONEDITIONABLE PACKAGE PKG_POLICYS AS 

/* PROCEDURE START */
	PROCEDURE PROC_MB_SEL(
		IN_MB_ID		IN		VARCHAR2,
		O_CUR			OUT		SYS_REFCURSOR
	);
	
	PROCEDURE PROC_PO_DEL(
		IN_P_ID			IN		VARCHAR2
	);
	
	PROCEDURE PROC_PO_INS(
		IN_P_LEVEL		IN		VARCHAR2,
		IN_P_SDATE		IN		VARCHAR2,
		IN_P_EDATE		IN		VARCHAR2,
		IN_P_PRIVATE	IN		VARCHAR2,
		IN_P_ENTER		IN		VARCHAR2,
		IN_P_REST		IN		VARCHAR2,
		IN_MB_ID		IN		VARCHAR2,
		IN_P_LINK		IN		VARCHAR2
	);
	
	PROCEDURE PROC_PO_UPD(
		IN_P_ID			IN		VARCHAR2,
		IN_P_PRIVATE	IN		VARCHAR2,
		IN_P_ENTER		IN		VARCHAR2,
		IN_P_REST		IN		VARCHAR2,
		IN_P_LINK		IN		VARCHAR2
	);
/* PROCEDURE END */

END PKG_POLICYS;


/******************************************************************************/


create or replace NONEDITIONABLE PACKAGE BODY PKG_POLICYS AS
	
	PROCEDURE PROC_MB_SEL(
		IN_MB_ID		IN		VARCHAR2,
		O_CUR			OUT		SYS_REFCURSOR
	) AS
	BEGIN
		
		
		OPEN O_CUR FOR
		SELECT P_ID,TO_CHAR(P_SDATE,'YYYY-MM-DD') AS P_SDATE,TO_CHAR(P_EDATE,'YYYY-MM-DD') AS P_EDATE,P_LEVEL,P_PRIVATE,P_ENTER,P_REST,MB_ID,P_LINK,
			CASE
				WHEN P_SDATE > SYSDATE THEN
					'Y'
				ELSE 
					'N'
			END AS UPDYN
		FROM POLICYS
		WHERE MB_ID = IN_MB_ID
		ORDER BY P_SDATE DESC, P_ID DESC
		;

	END PROC_MB_SEL;
	
	PROCEDURE PROC_PO_DEL(
		IN_P_ID			IN		VARCHAR2
	) AS
	BEGIN
	
		DELETE FROM POLICYS
		WHERE P_ID = IN_P_ID
		;
	
	END PROC_PO_DEL;
	
	PROCEDURE PROC_PO_INS(
		IN_P_LEVEL		IN		VARCHAR2,
		IN_P_SDATE		IN		VARCHAR2,
		IN_P_EDATE		IN		VARCHAR2,
		IN_P_PRIVATE	IN		VARCHAR2,
		IN_P_ENTER		IN		VARCHAR2,
		IN_P_REST		IN		VARCHAR2,
		IN_MB_ID		IN		VARCHAR2,
		IN_P_LINK		IN		VARCHAR2
	) AS
		V_P_ID					CHAR(4);
	BEGIN
		
		SELECT 'P'||TO_CHAR(TO_NUMBER(SUBSTR(NVL(MAX(P_ID),'P000'),2))+1,'FM000')
		INTO V_P_ID
		FROM POLICYS
		;
		
		INSERT INTO POLICYS (P_ID,P_SDATE,P_EDATE,P_LEVEL,P_PRIVATE,P_ENTER,P_REST,MB_ID,P_LINK)
		VALUES (V_P_ID,TO_DATE(IN_P_SDATE,'MM/DD/YYYY'),TO_DATE(IN_P_EDATE,'MM/DD/YYYY'),IN_P_LEVEL,IN_P_PRIVATE,IN_P_ENTER,IN_P_REST,IN_MB_ID,IN_P_LINK)
		;
	
	END PROC_PO_INS;
	
	PROCEDURE PROC_PO_UPD(
		IN_P_ID			IN		VARCHAR2,
		IN_P_PRIVATE	IN		VARCHAR2,
		IN_P_ENTER		IN		VARCHAR2,
		IN_P_REST		IN		VARCHAR2,
		IN_P_LINK		IN		VARCHAR2
	) AS
	BEGIN
		
		UPDATE POLICYS
		SET P_PRIVATE = IN_P_PRIVATE,
			P_ENTER = IN_P_ENTER,
			P_REST = IN_P_REST,
			P_LINK = IN_P_LINK
		WHERE P_ID = IN_P_ID
		;
		
	END PROC_PO_UPD;
	
END PKG_POLICYS;